### ISSUE TITLE
emacs 27.1 support

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/regent-mode#1]
It looks like rx-form was removed in emacs 27.1 so regent-mode no longer loads.

**Comment by syamajala** [comment]
See: https://github.com/immerrr/lua-mode/blob/master/lua-mode.el#L194-L195

**Comment by elliottslaughter** [comment]
This is related to https://github.com/terralang/terra-mode/issues/1, and like that issue can probably be fixed by rebasing on a newer lua-mode.

**Comment by syamajala** [comment]
Can the rebase branch be merged into master?

**Comment by elliottslaughter** [comment]
Done, sorry it took so long.
